version: '3.8'

services:
  nuxt-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nuxt-ssr-app
    ports:
      - "7000:7000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - HOST=0.0.0.0
      - PORT=7000
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=7000
      - APP_NAME=${APP_NAME:-Equipo.Guru}
      - API_BASE_URL=${API_BASE_URL:-http://localhost:7000/api}
      - AUTH_SECRET=${AUTH_SECRET:-your-secret-key}
    networks:
      - nuxt-network
    restart: unless-stopped

networks:
  nuxt-network:
    driver: bridge