
services:
  ss-schneiderservices:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: schneiderservices
    ports:
      - "${PORT:-7000}:${PORT:-7000}"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - HOST=0.0.0.0
      - PORT=${PORT:-7000}
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=${PORT:-7000}
      - APP_NAME=${APP_NAME:-Equipo.Guru}
      - API_BASE_URL=${API_BASE_URL:-http://localhost:7000/api}
      - AUTH_SECRET=${AUTH_SECRET:-your-secret-key}
    networks:
      - schneider-network
    restart: unless-stopped

  

networks:
  schneider-network:
    driver: bridge