name: Deploy Schneider Solutions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Acceder al VPS y actualizar la app
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Navegar al directorio de la app
            cd /var/www/SS-SchneiderSolutions

            # Obtener la última versión del código desde el repositorio
            git fetch --all
            git reset --hard origin/main

            # Construir y desplegar el contenedor con docker-compose
            docker-compose up --build -d

            # (Opcional) Verifica si todo se levantó correctamente
            docker ps
