name: Deploy Schneider Solutions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          script: |
            cd /var/www/SS-SchneiderSolutions
            
            # Guardar el contenedor actual
            docker-compose down
            
            # Actualizar código
            git fetch --all
            git reset --hard origin/main
            
            # Eliminar imágenes antiguas
            docker-compose rm -f
            docker system prune -f
            
            # Reconstruir y levantar
            docker-compose up --build -d