name: Deploy Nuxt.js to Docker

on:
  push:
    branches:
      - main  # Este flujo se ejecutará cuando haya un push en la rama 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Utilizamos un contenedor Ubuntu en GitHub Actions para correr el proceso

    steps:
      # Paso 1: Checkout del código en GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configuración SSH (para conectarse al VPS)
      - name: Setup SSH key for VPS
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}  # Clave privada SSH configurada en los Secrets

      # Paso 3: Conectar al servidor VPS y desplegar la aplicación
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            # Navegar al directorio de la aplicación en el servidor
            cd /path/to/your/project  # Reemplaza con la ubicación de tu proyecto en el VPS

            # Obtener la última versión del código
            git pull origin main

            # Detener los contenedores antiguos
            docker-compose down

            # Construir y levantar los contenedores nuevamente
            docker-compose up --build -d

            # (Opcional) Verificar que los contenedores estén corriendo
            docker ps
          EOF
